-- sudo su postgres
-- createuser clothes_user
-- createdb clothes_db --owner clothes_user
-- psql
-- alter user clothes_user with password '12345';
-- \q
-- psql clothes_db

--MARCAS
DROP TABLE IF EXISTS brands CASCADE;
CREATE TABLE brands (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"origin" character varying(100)
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON brands FROM public;
GRANT ALL ON brands TO clothes_user;

--PRODUCTOS
DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"price" integer,
"stock" integer,
"gender" integer,
"id_brand" integer,
   CONSTRAINT fk_brands
          FOREIGN KEY(id_brand) 
              REFERENCES brands(id)
              ON DELETE CASCADE 
);


REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON products FROM public;
GRANT ALL ON products TO clothes_user;


--BRANDS
INSERT INTO brands (name,origin) VALUES ('Nike', 'USA');
INSERT INTO brands (name,origin) VALUES ('Adidas', 'España');
INSERT INTO brands (name,origin) VALUES ('Puma', 'USA');
INSERT INTO brands (name,origin) VALUES ('Bol', 'Bolivia');

--PRODUCTS
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('pantalones', 2000, 6, 1,1);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('camiseta', 2200, 4, 1,,2);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('chaqueta', 1000, 1, 1,3);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('camisa', 3300, 7, 1,4);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('calcetines', 500, 0, 1,1);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('blusa', 1800, 1, 2,2);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('vestido', 4500, 4, 2,3);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('falda', 3000, 2, 2,4);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('medias', 1000, 0, 2,1);
INSERT INTO products (name, price, stock, gender, id_brand) VALUES ('zapatos de tacón', 3400, 3, 2,2);

-- \q
-- exit